# Pythonで配列のサイズ(numpy.shape)
## https://qiita.com/okd46/items/dec0f9482d5c76466575

In [6]:
import numpy as np
#5×3の行列を作成(要素は全て0)

a=np.array([[0]*3 for i in range(5)])

In [12]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
print(str(a))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
print("a=" + str(a))

a=[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
print(a.shape)

(5, 3)
