# NumPy配列ndarrayの形状を変換するreshapeの使い方と-1の意味
## https://note.nkmk.me/python-numpy-reshape-usage/

### ndarray.reshape()メソッドの使い方

In [2]:
import numpy as np

a = np.arange(24)

print(a)
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

print(a.shape)
# (24,)

print(a.ndim)
# 1

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
1


In [3]:
a_4_6 = a.reshape([4, 6])

print(a_4_6)
# [[ 0  1  2  3  4  5]
#  [ 6  7  8  9 10 11]
#  [12 13 14 15 16 17]
#  [18 19 20 21 22 23]]

print(a_4_6.shape)
# (4, 6)

print(a_4_6.ndim)
# 2

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
2


In [10]:
print('\n------------------------1----------------------------\n')
display(a.reshape(1,24))
print('\n------------------------2----------------------------\n')
display(a.reshape(1,1,24))
print('\n------------------------3----------------------------\n')
display(a.reshape(2,12))
print('\n------------------------4----------------------------\n')
display(a.reshape(2,2,6))
print('\n------------------------5----------------------------\n')
# display(a.reshape(1))#これはエラーになる
print('\n------------------------6----------------------------\n')
display(a.reshape(-1))
print('\n------------------------7----------------------------\n')
display(a.reshape(-1,24))
print('\n------------------------8----------------------------\n')
display(a.reshape(-1,2))
print('\n------------------------9----------------------------\n')
display(a.reshape(-1,2,2,1))


------------------------1----------------------------



array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])


------------------------2----------------------------



array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])


------------------------3----------------------------



array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])


------------------------4----------------------------



array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])


------------------------5----------------------------


------------------------6----------------------------



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])


------------------------7----------------------------



array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])


------------------------8----------------------------



array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])


------------------------9----------------------------



array([[[[ 0],
         [ 1]],

        [[ 2],
         [ 3]]],


       [[[ 4],
         [ 5]],

        [[ 6],
         [ 7]]],


       [[[ 8],
         [ 9]],

        [[10],
         [11]]],


       [[[12],
         [13]],

        [[14],
         [15]]],


       [[[16],
         [17]],

        [[18],
         [19]]],


       [[[20],
         [21]],

        [[22],
         [23]]]])